name: EntityTracker
main: com.yahoo.tracebachi.EntityTracker.EntityTrackerPlugin
author: Trace Bachi (BigBossZee, tracebachi@yahoo.com)
version: 1.2
commands:
  track:
    description: Output the top locations where entities of a type are located.
  tracktile:
    description: Output the top locations where tiles of a type are located.
  tracksum:
    description: Output a summary amount of all the entities in the world.
  trackreload:
    description: Reloads the configuration file.
permissions:
  EntityTracker.Use:
    description: Allows the use of the /track and /tracksum command.