name: EntityTracker
main: com.gmail.tracebachi.EntityTracker.EntityTracker
author: Trace Bachi (BigBossZee, tracebachi@gmail.com)
version: ${project.version}
commands:
  tracktp:
    description: Teleports to an entity on previously generated list.
  trackentity:
    description: Output the top locations where entities of a type are located.
  tracktile:
    description: Output the top locations where tiles of a type are located.
  tracksum:
    description: Output a summary amount of all the entities in the world.
  trackreload:
    description: Reloads the configuration file.
permissions:
  EntityTracker.Use:
    description: Allows the use of all EntityTracker commands.
